#pragma once

// Fleye
#define FLEYE_RANGE 900

// Scryo
#define SKRYO_RANGE 900

// Jumpkin
#define JUMPKIN_HORIZONTAL_RANGE 900
#define JUMPKIN_VERTICAL_RANGE 150

#define JUMPKIN_SPRITE_HEIGHT 43
#define JUMPKIN_SPRITE_WIDTH 32
#define JUMPKIN_SPRITE_WIDTH_SHORT 30

#define JUMPKIN_JUMP_ANIMATION_TIME 2

// Slime
#define SLIME_IDLE_SPRITE_WIDTH 31
#define SLIME_IDLE_SPRITE_HEIGHT 23

#define SLIME_ACTION_SPRITE_WIDTH 33
#define SLIME_ACTION_SPRITE_HEIGHT 24

#define SLIME_JUMP_ANIMATION_TIME 2